### ISSUE TITLE
is this a normal situation

### ISSUE THREAD

**Issue by ShiChen28** [yilinliu77/NVDNet#4]
Thank you for sharing this excellent work! 
I noticed that there seems to be some gaps in the extracted model, is this a normal situation?
![图片1](https://github.com/user-attachments/assets/ab84aebb-312a-4ba3-ac6b-3f0393638c5c)

**Comment by yilinliu77** [comment]
Yes it's normal if we do not use the curve to trim that surface. Then the surface is made by finding the alpha shape based on the sample points.

**Comment by ShiChen28** [comment]
> Yes it's normal if we do not use the curve to trim that surface. Then the surface is made by finding the alpha shape based on the sample points.

Thank you for your reply ! 
I was wondering if there is any code for surface trimming in the current repository, or if there are any methods available to help achieve watertight results ?

**Comment by yilinliu77** [comment]
We didn't clean up this part. Maybe you can refer to [BRepGen's postprocessing](https://github.com/samxuxiang/BrepGen/blob/main/sample.py) to get a valid solid model using opencascade.

**Comment by ShiChen28** [comment]
OK, I understand! 
Thank you for your patient explanation！
